FROM python:3.10

WORKDIR /app

COPY frontend /app
COPY data /app/data

RUN pip install --no-cache-dir streamlit requests pillow

EXPOSE 8501

CMD ["streamlit", "run", "streamlit_app.py", "--server.port=8501", "--server.address=0.0.0.0"]

