version: "3.9"

services:
  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile.api
    container_name: quality_api
    ports:
      - "8000:8000"
    restart: always
    volumes:
      - ../data:/app/data

  frontend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.frontend
    container_name: quality_frontend
    ports:
      - "8501:8501"
    depends_on:
      - api
    restart: always
    volumes:
      - ../frontend:/app           # streamlit_app.py'nin bulunduğu klasör
      - ../data:/app/data
